logging:
    level:
        root: WARN
        co.com.usc: DEBUG

spring:
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        username: alojamiento
        password: usc2024*
        jdbc-url: jdbc:postgresql://0.0.0.0:5432/hostalusc
        hikari:
            connection-timeout: 600000
            #maximum idle time for connection
            idle-timeout: 30000
            # maximum lifetime in milliseconds of a connection in the pool after it is closed.
            max-lifetime: 60000
            # maximum size that the pool is allowed to reach, including both idle and in-use connections
            maximum-pool-size: 16
            schema: usc
            driver-class-name: org.postgresql.ds.PGSimpleDataSource
            connection-test-query: select * from common.types limit 1;
    jpa:
        show-sql: false
        hibernate:
            ddl-auto: update
        properties:
            jakarta.persistence.sharedCache.mode: NONE
    jackson:
        serialization:
            INDENT_OUTPUT: true

